AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an EC2 linux web and sftp server in a dmz subnet using docker, nginx, and nodejs. Attaches an Elastic IP to the web server.
Mappings:
  RegionImageMap:
    "eu-west-1":
      "LinuxWebSftpServer": "ami-0312d6710b34339f9"
Resources:
  WebSftpLinux101:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: teal-web-linux-101
        - Key: Image
          Value: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxWebSftpServer"] 
      ImageId: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxWebSftpServer"]
      InstanceType: t2.medium
      KeyName: grox_key_aws_dmzserver
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          PrivateIpAddress: 10.181.4.101
          SubnetId: !ImportValue GroxTealDmzSubnet
          DeviceIndex: 0
          GroupSet: 
            - !ImportValue GroxTealWebSecurityGroup
            - !ImportValue GroxTealEdiSecurityGroup

