AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a basic EC2 linux postgres database server in a private subnet.
Mappings:
  RegionImageMap:
    "eu-west-1":
      "LinuxDbbox": "ami-0dc99832528906ec8"
Resources:
  DbBoxLinux101:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: teal-db-linux-102
        - Key: Image
          Value: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxDbbox"] 
      ImageId: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxDbbox"]
      InstanceType: t2.medium
      KeyName: grox_key_aws_prvserver
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeleteOnTermination: true
          PrivateIpAddress: 10.181.12.101		  
          SubnetId: !ImportValue GroxTealPrvSubnet
          DeviceIndex: 0
          GroupSet: 
            - !ImportValue GroxTealPrivateSecurityGroup
