AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a basic EC2 linux development machine in a development subnet.
Mappings:
  RegionImageMap:
    "eu-west-1":
      "LinuxDevbox": "ami-0102d955494c55f30"
Resources:
  DevBoxLinux101:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: teal-dev-linux-101
        - Key: Image
          Value: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxDevbox"] 
      ImageId: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxDevbox"]
      InstanceType: t2.micro
      KeyName: grox_key_aws_devuser
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !ImportValue GroxTealDevSubnet
          DeviceIndex: 0
          GroupSet: 
            - !ImportValue GroxTealDevSecurityGroup
