AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an EC2 linux web and sftp server in a dmz subnet using docker, nginx, and nodejs. Attaches an Elastic IP to the web server.
Mappings:
  RegionImageMap:
    "eu-west-1":
      "LinuxWebSftpServer": "ami-062417f18ca5781cb"
Resources:
  WebSftpLinux101:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: Name
          Value: teal-web-linux-101
        - Key: Image
          Value: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxWebSftpServer"] 
      ImageId: !FindInMap [RegionImageMap, !Ref "AWS::Region", "LinuxWebSftpServer"]
      InstanceType: t2.micro
      KeyName: grox_key_aws_dmzserver
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          PrivateIpAddress: 10.181.4.101
          SubnetId: !ImportValue GroxTealDmzSubnet
          DeviceIndex: 0
          GroupSet: 
            - !ImportValue GroxTealWebSecurityGroup
            - !ImportValue GroxTealEdiSecurityGroup
# Uncomment if there is an elastic IP you want to associate with this box
#  TheraHermElasticIpAssociation:
#    Type: AWS::EC2::EIPAssociation 
#    Properties: 
#      AllocationId: eipalloc-0ae4148ea8d3df390
#      InstanceId: !Ref WebSftpLinux101

